Add 'options' argument in mkProxy(), add specific interfaces and allo…
partnering/node-dbus pull request #34
Opened 2018-12-20 10:42 UTC by FredericAMAN

…w to add new interfaces when specific proxy (#33)

2019-01-01 21:45 UTC, antoineDeRengerve requested changes
Some changes expected for maintainability : comments, etc.

One real question about managing interfaceRemoved when not all interfaces/objects are loaded.

2019-01-01 21:45 UTC, antoineDeRengerve commented on lib/DBusProxy.js
> +		debug(`Introspection done, this:\n${inspect(this, {depth: 7})}`)
Should debug message remain ? With depth is 7 ? Is it always 7 ?

2019-01-01 21:45 UTC, antoineDeRengerve commented on lib/DBusProxy.js
> +					debug(`In '${path}', no targeted interface`)
Actually targetting all interfaces because they will be all loaded

2019-01-01 21:45 UTC, antoineDeRengerve commented on lib/DBusProxy.js
> +DBusProxy.prototype.pathsAreIncluded = function (path1, path2) {
Comment function

2019-01-01 21:45 UTC, antoineDeRengerve commented on lib/DBusProxy.js
> +					} else if (newDepth > 0) {
Add a comment : why newDepth must be >0

2019-01-01 21:45 UTC, antoineDeRengerve commented on lib/DBusProxy.js
> +									if (signalName === 'InterfacesRemoved') {
What if an interface that was not managed is removed ? Does it make the library crash ?
Have you tested ?

2019-01-08 13:25 UTC, FredericAMAN commented
@antoineDeRengerve I did some modifications according to your comments

2019-01-12 22:35 UTC, antoineDeRengerve commented on lib/DBusProxy.js
> +		debug(`Introspection done, this:\n${inspect(this, {depth: 7})}`)
So ?

2019-01-12 22:37 UTC, antoineDeRengerve commented on lib/DBusProxy.js
> +									if (signalName === 'InterfacesRemoved') {
The change seems ok with respect to this question. I assume, you have tested.

2019-01-12 22:38 UTC, antoineDeRengerve commented
Please provide replies to remaining questions.

2019-01-14 11:48 UTC, FredericAMAN commented on lib/DBusProxy.js
> +		debug(`Introspection done, this:\n${inspect(this, {depth: 7})}`)
Yes it should, to help for debugging by displaying the final proxy object. By default, introspection deep is 2. 7 is to show deeper

2019-01-14 12:01 UTC, FredericAMAN commented
Ok, it's done

2019-01-14 14:45 UTC, antoineDeRengerve approved these changes

2019-01-14 14:46 UTC, merged